# Generated by Django 3.2.5 on 2021-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becomarketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='productImages'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
